### PR TITLE
Hero Section

### LINKED ISSUE #1: Hero: Add hero section
Here is a low-fidelity prototype of what is desired on the desktop.

Hero

- [ ] Hovering on the Knight should show sparks
- [ ] Clicking on the Knight must scroll down to the competitions section
- [ ] Hovering on the Bard should show singing notes
- [ ] Clicking on the Bard should scroll down to the events section
- [ ] Also add a Call To Action button like 'Get Started' with the link to the Unstop/PayTM Inci events page (will be provided)

On mobile, the assets and the text should be aligned vertically and not horizontally.

Note: The Incident Media team will provide the Knight and the Bard.

### LINKED ISSUE #20: Navbar: Modify navbar section
- [ ] Make the navbar sticky with the hero section in background initially
- [ ] Add the newly added section links
- [ ] Add the 'Register' button

### PR DESCRIPTION
**Pull request by ahmedfahim21**
### Navbar Hero section

**Changes made**
- Added heading, description and buttons
- Added bard and knight assets 
- Added some basic hover effects
- modified the gradients to suit the colour theme 
- Added fonts

**Todo**
- Add the hover animations for knight and bard
- Add the onclick links to respective sections
- Add animations

**Issue Reference**
> closes #1 
> closes #20

### CODE REVIEW

**Comment by mittal-parth** [comment]
@ahmedfahim21 Good work!

I'll show this to the team today but most likey we'll have something more grand. The video shared to you will most likely be the background. The typography and layout are good.

**Comment by mittal-parth** [comment]
@ahmedfahim21 
I think you should keep the the things like this:


annotely_image

**Comment by ahmedfahim21** [comment]
Ok @mittal-parth, will do the changes!!

**Comment by mittal-parth** [comment]
@ahmedfahim21 
It's now starting to look really good! 🔥 

Though it still requires a lot of changes

- [ ] The centring is an issue. The problem is with the asset itself. Is there a possibility of us cropping it?
- [ ] The Navbar is eating up the grandeur of the hero section. Having the links _over_ the hero itself without the current background would be nicer. We could either keep all the links open or hide them the way they are on the phone. Upon scrolling, if we decide to keep a sticky navbar, it can appear with the current blackish background, otherwise no need.
- [ ] Its responsive for phones and tablets but not for laptops. On my monitor its fine. However, on my laptop it gets screwed up because of the relative positioning I think. Also, the background is getting cropped. Attaching a laptop screenshot here

image

**Comment by ahmedfahim21** [comment]
> @ahmedfahim21 It's now starting to look really good! fire
> 
> Though it still requires a lot of changes
> 
> * [ ]  The centring is an issue. The problem is with the asset itself. Is there a possibility of us cropping it?
> * [ ]  The Navbar is eating up the grandeur of the hero section. Having the links _over_ the hero itself without the current background would be nicer. We could either keep all the links open or hide them the way they are on the phone. Upon scrolling, if we decide to keep a sticky navbar, it can appear with the current blackish background, otherwise no need.
> * [ ]  Its responsive for phones and tablets but not for laptops. On my monitor its fine. However, on my laptop it gets screwed up because of the relative positioning I think. Also, the background is getting cropped. Attaching a laptop screenshot here
> 
> image

@mittal-parth 

- I'll try cropping the video myself and see if it works. If not, then probably we need to ask them to do it and send.
- Yeah, felt the same about the NavBar. Is it fine if I create a new issue for it and assign it to myself?
- Not sure why it happened, but will see how to make it responsive for different laptop screen and fix it.

**Comment by mittal-parth** [comment]
> * Yeah, felt the same about the NavBar. Is it fine if I create a new issue for it and assign it to myself?

Anything works

**Pull request merged**
