### PR TITLE
FAQ

### LINKED ISSUE #19: FAQ: Add FAQ Section
Reference: https://ethindia.co/

### PR DESCRIPTION
**Pull request by marcdhi**
### FAQ

> Added a basic layout for the faq section
> Yet to add responsive 
### Any points to be carefully reviewed?
Review the design

### CODE REVIEW

**Comment by mittal-parth** [comment]
Looks nice! Responsiveness is on point

- Maybe different font will look better
- Reduce the gap between each question? Probably you can provide a sample. If it doesn't look well, we'll go ahead with the current design

**Comment by marcdhi** [comment]
@mittal-parth ok working on the feedbacks

**Comment by mittal-parth** [comment]
Font looks good!
Overall looks good. 
I still feel the asset can be better?

Try Dall-E?

**Comment by mittal-parth** [comment]
Manuscript

Try this? Used Dall-E xD
The problem is the edges cutting from the top :(

**Comment by mittal-parth** [comment]
https://lottiefiles.com/96517-orange-question

Or try this one. Change the colours to match our scheme a bit (darker colours like the Inci logo) and I think this will work

**Pull request merged**
