### PR TITLE
Events

### LINKED ISSUE #2: Events: Add events section
References:

1. https://bits-oasis.org/

https://user-images.githubusercontent.com/76661350/215050985-04795bfa-e908-4312-8aa9-27edf6406370.mp4

2. https://lottiefiles.com/why-motion

https://user-images.githubusercontent.com/76661350/215051412-c76f3b0d-63d4-467d-a0ae-cf2a9b6167b4.mp4

- [ ] Clicking on each card must reveal more information
- [ ] The card should spin and open to reveal more information if possible 
- [ ] The design must be responsive (like bits oasis)
- [ ] The list of events and the corresponding images will be provided by the Inci Media Team.

### PR DESCRIPTION
**Pull request by ayush4345**
### PR description

Added events carousel and added a popup when we clicked on event image. Popup closing opening is animated

### Any points to be carefully reviewed?

Check the animation of the closing and opening of the popup

closes #2

### CODE REVIEW

**Comment by ayush4345** [comment]
check if this rotation animation looks good or not

**Comment by mittal-parth** [comment]
@ayush4345 Looks nice especially the modal!

Some comments:

- Each event card can be bigger
- Try to keep it like bits oasis where the card in focus is slightly higher than the rest
- Add shadow to the cards
- Keep the corners rounded 
- The modal animation is really good except for the fact that opening and closing can a little smoother. The closing seems a little abrupt

**Comment by mittal-parth** [comment]
Really good improvements from before! 🔥 
- [ ] Use the correct fonts
- [ ] Wasn't it supposed to be different on phone? Like the one on bits oasis?
- [ ] Rebase it off `testing` to see full preview and new changes. Resolve conflicts (if they arise)

**Comment by mittal-parth** [comment]
Rebase off main and resolve conflicts

**Comment by mittal-parth** [comment]
Niice!

- The section is going beyond the usual limits of the website. 
- Make everything smaller, basically 
- Font size for the heading is bigger than the rest
- Keep Sunidhi in the center (coming soon came first)
- Edges arent rounded on phone?

**Review by mittal-parth — CHANGES_REQUESTED** [review]
Niice!

- [x] The section is going beyond the usual limits of the website. 
- [x] Make everything smaller, basically 
- [x] Font size for the heading is bigger than the rest
- [x] Keep Sunidhi in the center (coming soon came first)
- [x] Edges arent rounded on phone?
- [x] The modal text is too close the image. Have sufficient padding like competitions

**Comment by mittal-parth** [comment]
- [x] Events heading font size is larger than the rest 
- [ ] The edges are weirdly rounded on phone?
- [x] Keep date format like 17th March (year not required)
- [x] Rebase off main

**Comment by ayush4345** [comment]
Weirdly means ?

**Pull request merged**
